-- liquibase formatted sql

-- changeset create:product
CREATE TABLE product
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description ,
    creationDate TIMESTAMP DEFAULT current_timestamp,
    modificationDate DATE;
    category ;
)